export const START_FETCH_USERS_DATA = 'START_FETCH_USERS_DATA';
export const FINISH_FETCH_USERS_DATA = 'FINISH_FETCH_USERS_DATA';
export const ERROR_FETCH_USERS_DATA = 'ERROR_FETCH_USERS_DATA';

export const START_SEND_FORM_DATA = 'START_SEND_FORM_DATA';
export const FINISH_SEND_FORM_DATA = 'FINISH_SEND_FORM_DATA';
export const ERROR_SEND_FORM_DATA = 'ERROR_SEND_FORM_DATA';
export const EDIT_USER_FORM_DATA = 'EDIT_USER_FORM_DATA';
export const RESET_FORM_DATA = 'RESET_FORM_DATA';

export const DELETE_CARD = 'DELETE_CARD';